export const siteConfig = {
  name: "FirstMartt",
  tagline: "India's Hyperlocal Commerce Platform for Local Businesses",
  description:
    "FirstMartt is an AI-powered hyperlocal marketplace startup in India connecting local businesses, merchants, and customers through a multi-vendor digital commerce platform.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.firstmartt.com",
  locale: "en_IN",
  language: "en",
  founder: {
    name: "FirstMartt Team",
    role: "Founders",
    /** Brief bio for Person schema and founder authority pages */
    bio: "Building India's hyperlocal commerce infrastructure to empower local businesses, merchants, and communities through technology.",
  },
  contact: {
    email: "firstmartsindia@gmail.com",
    phone: {
      countryCode: "+91",
      national: "8261807358",
      /** E.164 display for international visitors */
      international: "+91 8261807358",
      /** Used in tel: links */
      e164: "+918261807358",
      /** Used in wa.me links (digits only, no +) */
      whatsappId: "918261807358",
    },
    address: {
      streetAddress: "India",
      addressLocality: "Yavatmal",
      addressRegion: "Maharashtra",
      addressCountry: "IN",
      postalCode: "445301",
    },
  },
  social: {
    twitter: "@firstmartt",
    linkedin: "https://linkedin.com/company/firstmartt",
  },
  /** Analytics & verification IDs (loaded from environment variables) */
  analytics: {
    gaId: process.env.NEXT_PUBLIC_GA_ID ?? "",
    gscVerification: process.env.GOOGLE_SITE_VERIFICATION ?? "",
    bingVerification: process.env.BING_SITE_VERIFICATION ?? "",
  },
  keywords: [
    // Brand keywords (Tier A)
    "FirstMartt",
    "FirstMartt India",
    "FirstMartt startup",
    "FirstMartt investment",
    "FirstMartt funding",
    "FirstMartt business model",
    "FirstMartt ecommerce",
    "FirstMartt app",
    "FirstMartt founders",
    "FirstMartt Yavatmal",
    // Business & Marketplace keywords (Tier B - Competitor & Market-Aligned)
    "Hyperlocal Commerce Startup",
    "Hyperlocal Marketplace India",
    "Local Commerce Platform",
    "Multi Vendor Marketplace India",
    "Digital Platform for Local Businesses",
    "Local Business Marketplace",
    "Local merchant digitalization India",
    "Kirana store digital platform",
    "Quick commerce Tier 2 Tier 3 India",
    "Quick commerce without dark stores",
    "AI Commerce Startup India",
    "Retail Technology Startup",
    "Hyperlocal delivery platform India",
    "Neighbourhood store ecommerce",
    "Online marketplace for local shops",
    "Digitize local retail India",
    "Kirana e-commerce app",
    "Phygital retail platform India",
    "Kirana WhatsApp ordering system",
    "Digital storefront for local shops",
    "MSME retail digitization India",
    "Marketplace Startup",
    "Ecommerce Startup India",
    "Indian hyperlocal commerce startup",
    "hyperlocal commerce platform India",
    "local business digitalization India",
    // Investor & Funding keywords (Tier B — Indian Angels & VCs)
    "Startup Seeking Investment India",
    "Startup Investment Opportunity",
    "Invest in Indian Startup",
    "Pre-Seed Startup India",
    "Seed Stage Commerce Startup",
    "Angel Investment Opportunity",
    "Venture Capital Startup India",
    "Indian Ecommerce Startup Investment",
    "Hyperlocal Startup Investment",
    "Indian Retail Technology Startup",
    "Invest in Indian Tech Startups",
    "Retail tech angel investment India",
    "Indian Startup",
    "Indian startup investment opportunity",
    "Indian ecommerce startup investment",
    "hyperlocal startup investment",
    "Indian retail technology startup",
    // Investor & Funding keywords (Tier B — Foreign/NRI/FDI)
    "FDI India ecommerce",
    "NRI investment Indian startups",
    "foreign investment Indian retail tech",
    "India ecommerce investment",
    "invest in Indian startups",
    "India market entry ecommerce",
    "India Startup Investment Opportunity 2026",
    // Regional & Location keywords (Tier B — Regional)
    "Hyperlocal ecommerce Maharashtra",
    "Local commerce startup Yavatmal",
    "Tier 2 city commerce India",
    "Tier 3 city retail digitization",
    "Vidarbha startup ecosystem",
    "Maharashtra retail tech startup",
    "Hyperlocal shopping Maharashtra",
    // Informational & High-Intent Long-Tail queries (Tier C)
    "what is hyperlocal commerce",
    "future of hyperlocal commerce in India",
    "hyperlocal commerce business model",
    "How local merchants can sell online in India",
    "Unit economics of hyperlocal delivery",
    "Why Tier 2 and Tier 3 cities are the future of Indian ecommerce",
    "Multi vendor marketplace vs single vendor",
    "AI in local retail supply chain India",
    "Dark store model vs local merchant network",
    "Tier-2 city ecommerce India",
    "Tier-3 city commerce India",
    "local merchant marketplace",
  ],
} as const;

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/why-firstmartt", label: "Why FirstMartt" },
  { href: "/solutions", label: "Solutions" },
  { href: "/investors", label: "Investors" },
  { href: "/blog", label: "Blog" },
  { href: "/contact", label: "Contact" },
] as const;

export const footerLinks = {
  company: [
    { href: "/about", label: "About Us" },
    { href: "/why-firstmartt", label: "Why FirstMartt" },
    { href: "/mission", label: "Our Mission" },
    { href: "/vision", label: "Our Vision" },
    { href: "/founder", label: "Founder Briefing" },
    { href: "/careers", label: "Careers" },
  ],
  platform: [
    { href: "/problem", label: "Problem We Solve" },
    { href: "/solutions", label: "Solutions Overview" },
    { href: "/for-customers", label: "For Customers" },
    { href: "/for-local-businesses", label: "For Local Businesses" },
    { href: "/for-delivery-partners", label: "For Delivery Partners" },
    { href: "/business-model", label: "Business Model" },
    { href: "/roadmap", label: "Roadmap" },
  ],
  investors: [
    { href: "/investors", label: "Investor Hub" },
    { href: "/investment", label: "Investment Opportunity" },
    { href: "/market", label: "Market Opportunity" },
    { href: "/traction", label: "Traction & Metrics" },
    { href: "/unit-economics", label: "Unit Economics" },
    { href: "/competitive-landscape", label: "Competitive Landscape" },
    { href: "/investors/faq-international", label: "International Investor FAQ" },
    { href: "/faq", label: "FAQ" },
    { href: "/blog", label: "Blog" },
  ],
  legal: [
    { href: "/privacy", label: "Privacy Policy" },
    { href: "/terms", label: "Terms & Conditions" },
    { href: "/contact", label: "Contact" },
  ],
} as const;


